/*
 * This file was automatically generated by EvoSuite
 * Fri Oct 26 19:27:17 GMT 2018
 */

package org.scoutant.blokish.model;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import org.scoutant.blokish.model.AI;
import org.scoutant.blokish.model.Board;
import org.scoutant.blokish.model.Game;
import org.scoutant.blokish.model.Move;
import org.scoutant.blokish.model.Piece;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AI_ESTest extends AI_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Game game0 = new Game();
      AI aI0 = new AI(game0);
      Piece piece0 = new Piece(3, 21, "sc", 20, 3);
      Piece piece1 = piece0.add(3, 3);
      aI0.overlaps(20, piece1, 3, 21);
      assertEquals(3, aI0.adaptedLevel);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Game game0 = new Game();
      AI aI0 = new AI(game0);
      Board board0 = new Board(3);
      Piece piece0 = board0.findPieceByType("Z5");
      boolean boolean0 = aI0.overlaps(3, piece0, 20, 0);
      assertEquals(3, aI0.adaptedLevel);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Game game0 = new Game();
      AI aI0 = new AI(game0);
      Board board0 = new Board(20);
      Piece piece0 = board0.findPieceByType("Z5");
      boolean boolean0 = aI0.overlaps(3, piece0, 20, 5);
      assertEquals(3, aI0.adaptedLevel);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Game game0 = new Game();
      AI aI0 = new AI(game0);
      Board board0 = new Board(3);
      Piece piece0 = board0.findPieceByType("Z5");
      boolean boolean0 = aI0.overlaps(0, piece0, (-583), 2);
      assertFalse(boolean0);
      assertEquals(3, aI0.adaptedLevel);
  }

  @Test
  public void test4()  throws Throwable  {
      Game game0 = new Game();
      AI aI0 = new AI(game0);
      Board board0 = new Board(20);
      Piece piece0 = board0.findPieceByType("Z5");
      Move move0 = new Move(piece0, 3, 48);
      // Undeclared exception!
      try { 
        aI0.chainingScore(0, move0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // android/util/Log
         //
         verifyException("org.scoutant.blokish.model.AI", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Game game0 = new Game();
      AI aI0 = new AI(game0);
      Board board0 = new Board(20);
      Piece piece0 = board0.findPieceByType("Z5");
      Move move0 = new Move(piece0, 3, 2);
      move0.j = (-1339);
      // Undeclared exception!
      try { 
        aI0.chainingScore(0, move0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // android/util/Log
         //
         verifyException("org.scoutant.blokish.model.AI", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      Game game0 = new Game();
      AI aI0 = new AI(game0);
      Board board0 = new Board(20);
      Piece piece0 = board0.findPieceByType("Z5");
      Move move0 = new Move(piece0, (-602), 5);
      // Undeclared exception!
      try { 
        aI0.chainingScore(0, move0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // android/util/Log
         //
         verifyException("org.scoutant.blokish.model.AI", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      Game game0 = new Game();
      AI aI0 = new AI(game0);
      Board board0 = new Board(20);
      Piece piece0 = board0.findPieceByType("Z5");
      Move move0 = new Move(piece0, 20, 2);
      // Undeclared exception!
      try { 
        aI0.chainingScore(0, move0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // android/util/Log
         //
         verifyException("org.scoutant.blokish.model.AI", e);
      }
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Game game0 = new Game();
      AI aI0 = new AI(game0);
      // Undeclared exception!
      try { 
        aI0.think(3, 3);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // android/util/Log
         //
         verifyException("org.scoutant.blokish.model.AI", e);
      }
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      Game game0 = new Game();
      AI aI0 = new AI(game0);
      // Undeclared exception!
      try { 
        aI0.hasMove(0);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // android/util/Log
         //
         verifyException("org.scoutant.blokish.model.AI", e);
      }
  }
}
