language: android
android:
  components:
    - build-tools-27.0.3
    - android-27
    - extra
    
dist: trusty
sudo: required
language: java
jdk: oraclejdk7

script:
 - #TODO: get infer archive and extract it
 - #TODO: add infer executable to the path
 - #TODO: invoke infer with your project