language: android
android:
  components:
    - build-tools-27.0.3
    - android-27
    - extra
  
  addons:
  sonarcloud:
    organization: "ecse429-fall2018"
    token:
      secure: "2e3073f1369a0d6355aeb3c6b56f2ab80e6d9a03"
