language: android
android:
  components:
    - build-tools-27.0.3
    - android-27
    - extra
  
  addons:
  sonarcloud:
    organization: "ecse429g7"
    token:
      secure: "c0c221349d00f6702d64808145f124de81a253ae"
