# branches:
#   except:
#   - inferElv

language: android
android:
  components:
    - build-tools-27.0.3
    - android-27
    - extra

cache:
  directories:
    # Gradle
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

# dist: trusty
# sudo: required
# language: java
# jdk: oraclejdk8

# script:
#   - curl https://github.com/facebook/infer/releases/download/v0.15.0/infer-linux64-v0.15.0.tar.xz
#   - tar -xvf infer-linux64-v0.15.0.tar.xz
#   - ./infer-linux64-v0.14.0/install-sh
#   - export infer = 
#   - #TODO: add infer executable to the path
#   - infer -- ./gradlew build
script:
- ./installInfer
